name: artiver
description: articles time saver

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  intl: ^0.17.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true
  generate: true

