name: Go

on: [push,pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
            
    - name: Run golangci-lint
      working-directory: ./server
      run: golangci/golangci-lint-action@v2.5.2

    - name: Build
      working-directory: ./server
      run: go build -v ./...

    - name: Test
      working-directory: ./server
      run: go test -v ./...
