name: flutter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0

      - name: Change Directoru
        run: cd app

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib

      - name: Analyze
        run: flutter analyze lib

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random